PASS: tests/test-30574
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
PASS: test/test-client.py 1 - <unittest.runner.TextTestResult run=36 errors=0 failures=0> (tap module not available)
PASS: test/test-exception-py3.py 1 - <unittest.runner.TextTestResult run=2 errors=0 failures=0> (tap module not available)
PASS: test/test-p2p.py 1 - <unittest.runner.TextTestResult run=4 errors=0 failures=0> (tap module not available)
PASS: test/test-signals.py 1 - <unittest.runner.TextTestResult run=10 errors=0 failures=0> (tap module not available)
PASS: test/test-standalone.py 1 - <unittest.runner.TextTestResult run=52 errors=0 failures=0> (tap module not available)
PASS: test/test-unusable-main-loop.py 1 - <unittest.runner.TextTestResult run=1 errors=0 failures=0> (tap module not available)
PASS: test/run-test.sh 1 - cross-test-client produced some output
PASS: test/run-test.sh 2 - cross-test-server produced some output
PASS: test/run-test.sh 3 - cross-test client reported no failures
PASS: test/run-test.sh 4 - cross-test server reported no untested functions
PASS: test/run-test.sh 5 - cross-test server: exit status 0
PASS: test/test-import-repeatedly 1 - was able to import dbus 100 times
# TOTAL: 12
# PASS:  12
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
